# Generated by Django 3.2.7 on 2021-12-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('batafsil', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('yangi', 'yangi'), ('bajarilgan', 'bajarilgan')], max_length=15)),
                ('vaqt', models.TimeField()),
            ],
        ),
    ]
